language: ruby
cache: bundler
rvm:
 - 2.2.3
notifications:
  email: false
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml 
  - psql -c "CREATE DATABASE ponypod_test;" -U postgres
script: xvfb-run -a bundle exec rake
